### ISSUE TITLE
Subtitle toggle button are duplicated

### ISSUE THREAD

**Issue by areeb111** [JMVTechnology/Clappr-Subtitle#11]
Hi,
I got two button icons for subtitle toggle ,
Check the screenshot
![ccbutton](https://cloud.githubusercontent.com/assets/2633763/26416282/01ccebf4-40be-11e7-9f96-6d45a41715c6.png)

Is there a way to remove the marked one ?

**Comment by areeb111** [comment]
I have made a temp. workaround by jQuery:
....
```
onPlay: function() {
                   $( ".media-control-subtitle-toggler" ).last().hide();
                   }
```

**Comment by tmaiadev** [comment]
Hello there, @areeb111 . In what browser is it happening? Or is it happening in all of them?

**Comment by areeb111** [comment]
@thalleshmm  All browsers

**Comment by tmaiadev** [comment]
Hello everyone. Thank you for noticing. Something changed in the latest version of Clappr and it's been causing this problem. It will be soon addressed and fixed.
