### ISSUE TITLE
Error with subtitle if one of lines is empty

### ISSUE THREAD

**Issue by alimohammed** [JMVTechnology/Clappr-Subtitle#13]
Hi Guys

I'm using clappr for my website with Clappr-subtitle plugin and there's a problem with subtitle.
Clappr won't view subtitle if the subtitle text is empty like the example below
From srt file:

```
150
00:08:40,140 --> 00:08:43,000
حتّى أنا أستطيع العودة إلى البيت مبكّرًا أحيانًا

151
00:08:43,800 --> 00:08:44,440


152
00:08:45,340 --> 00:08:46,000
ما الخطب؟

```

as you see at **151** there was no text so whenever srt parser come to this line all subtitles after this line won't appear.

you can find a copy of subtitle file here: [Subtitle file](http://esite-iq.com/clappr/subtitle.srt)

**Comment by tmaiadev** [comment]
Hello, thank you for filing this bug. I'll check it out later.

Unfortunately I'm running behind on my schedule, and it might be a while before I fix that bug. I'll look into that as soon as I can, I promise. But again, it might be a while.

**Comment by areeb111** [comment]
#14

**Comment by h4rpreet** [comment]
Was this fixed ?
