### ISSUE TITLE
Reload plugin after change the source

### ISSUE THREAD

**Issue by mikeevstropov** [JMVTechnology/Clappr-Subtitle#4]
Hi. We cant use ```configure``` to update ```srt``` file, it just not working.
We should create some stuff on ```bindEvents()``` method:
```this.listenTo(this.core.mediaControl, Events.MEDIACONTROL_CONTAINERCHANGED, this.reload) ```

**Comment by tmaiadev** [comment]
Hello!
We absolutely should! Could you explain a little more how you think it should work? Just to make sure we get it right.

**Comment by tmaiadev** [comment]
Done! =)
