### ISSUE TITLE
Multiline subtitle block

### ISSUE THREAD

**Issue by mikeevstropov** [JMVTechnology/Clappr-Subtitle#6]
Hi.
```
53
00:02:35,068 --> 00:02:39,137
Thit is the multiline
subtitle block.
```
For this example, player will show only last line "subtitle block.".

Because we sould use `+=` instead of `=` on line 248
https://github.com/JMVTechnology/Clappr-Subtitle/blob/master/subtitles.js#L248

Thank you.

**Comment by tmaiadev** [comment]
Hello, @mikeevstropov. Thank you for noticing, I'll fix it right alway =)
