### ISSUE TITLE
Font+ autostart

### ISSUE THREAD

**Issue by h4rpreet** [JMVTechnology/Clappr-Subtitle#7]
Hi,

First of all sorry for creating this as issue, i am new and i could not figureout how to post a request or question, so i choose this.

I wanted to ask you 

how can change the font (stype) of the subtitles visible on video ? I want to use this style setting- http://prntscr.com/ds4vqd 
Is there any way to add multiple subtitle track ? 
How can make it auto start when video plays ?

Thanks.

**Comment by h4rpreet** [comment]
Hello,

Alright we found how to auto start it.


Now only thing i need is fix the looks of it. We tried to play with it. Please help us. 

What it currently looks like:  http://prntscr.com/ds8dtg

How we want to make it look like: http://prntscr.com/ds8e33


Our is very small, Also i noticed that  Is it possible to make it responsive ? Like if we smaller the screen it goes smaller and if we bigger the screen, it goes bigger.

**Comment by h4rpreet** [comment]
Also i'd like to report that it works on some videos and it does not work on some vidoes, I've tried everything from adding random srt files and adding those srt files on different player and it works fine there.

Please update this mod to work flawless.

Regards.

**Comment by tmaiadev** [comment]
> First of all sorry for creating this as issue, i am new and i could not figureout how to post a request or question, so i choose this.

It's okay =) This is the right place.

> how can change the font (stype) of the subtitles visible on video ? I want to use this style setting
 
Well, you can change a few styles for now, but not the font itself. We'll implement it. For now you can change the **background color**, the **font color**, the **font size**, the **font weight** and the **text shadow**.  I believe though that styling the player wrapper with a different font will work.

> Is there any way to add multiple subtitle track ?

Unfortunately, not. Not yet. =(

> Our is very small, Also i noticed that Is it possible to make it responsive ? Like if we smaller the screen it goes smaller and if we bigger the screen, it goes bigger.

Nope, for now the font size you set on the setup will be the size that it will be rendered in any resolution. 

> Also i'd like to report that it works on some videos and it does not work on some vidoes, I've tried everything from adding random srt files and adding those srt files on different player and it works fine there.

Please, give us more info about the videos and srt files. We will be happy to fix it.

**Comment by h4rpreet** [comment]
Can you email you the details ? like video url and srt files.


I've managed to do everything. Only thing i need is now increasing size of subtitles a bit, which figure to change ?

Also please find some time to release a new version with more features like allowing viewer to edit font and position and few other features.

Regards.

**Comment by tmaiadev** [comment]
> Can you email you the details ? like video url and srt files.

Sure. My e-mail address is on my profile.

> I've managed to do everything. Only thing i need is now increasing size of subtitles a bit, which figure to change ?

Just change the fontSize attribute

```JS
 var player = new Clappr.Player({
    source: 'video.mp4',
    baseUrl: '/latest',
    mute: true,
    height: 360,
    width: 640,
    plugins: [ClapprSubtitle],
    subtitle : {
        src : "video.srt",
        fontSize : '14px', // You can change the size here
    },
});
player.attachTo(document.getElementById('player'));
```

> Also please find some time to release a new version with more features like allowing viewer to edit font and position and few other features.

We don't have plans of implementing this feature anytime soon. I'm sorry.
