### ISSUE TITLE
Subtitles don't work on some videos

### ISSUE THREAD

**Issue by h4rpreet** [JMVTechnology/Clappr-Subtitle#9]
Hi, i added post few days ago that subtitle don't work on some videos and you asked for an example.

I sent an example video+srt file few days ago in your email.

Can you check it ? I've more examples if you need it.

Regards

**Comment by tmaiadev** [comment]
Hello, I did check, thank you. Already working that =) Fix will be available soon. I'll let you know.

**Comment by h4rpreet** [comment]
Thanks buddy

**Comment by h4rpreet** [comment]
any update ?

**Comment by tmaiadev** [comment]
Still working on it, pal. I've been pretty busy lately. Sorry

**Comment by h4rpreet** [comment]
I hope this will be done anytime soon, If you want i can pay you for your time to add some extra features/fixes for me.

**Comment by h4rpreet** [comment]
Hello buddy,

If you don't have time to fix it, can you tell me what is the issue ? So i can ask someone else to fix it. We can't even find the problem actually, if you can tell where is the problem , we might fix it and contribute also here.

Thanks.

**Comment by tmaiadev** [comment]
It's very likely to be something in the **parseSubtitle** method. Not sure what though. It's open, feel free to ask anyone to contribute, I'll be more more than happy to accept the contribution =)

**Comment by tmaiadev** [comment]
I believe it is now fixed.
